// Generated by roc-apps tests/package.py. One row per ported test,
// in the shape src/cli/test/parallel_cli_runner.zig uses. The
// expected text is also in expected/<name>.txt, byte for byte.

const codex_act_let_scope_stdout =
    \\a: 2
    \\a-after: 2
    \\chain-in-body: 5
    \\chain-b: 3
    \\chain-c: 4
    \\chain-d: 5
    \\chain-sum: 14
    \\shadowed: 100
    \\shadowed-after: 100
    \\arm-local: 23
    ++ "\n";

const codex_amp_after_call_stdout =
    \\n=7
    ++ "\n";

const codex_arith_operand_order_stdout =
    \\43
    \\43
    ++ "\n";

const codex_arithmetic_stdout =
    \\clamp: 37
    \\absorb: 12
    \\match: answer/one/other
    \\clamping: 100
    \\even: yes
    \\odd: yes
    \\comma-params: 42/42
    \\concat-text: hello world
    \\concat-bool: False
    \\concat-list: 4
    ++ "\n";

const codex_arm64_boot_test_stdout =
    \\Codex ARM64 boot OK
    \\hello world
    ++ "\n";

const codex_bezier_identity_stdout =
    \\cubic-t0=100,200,300
    \\cubic-t1000=1000,1100,1200
    \\cubic-mid=550,650,750
    \\quad-t0=100,200,300
    \\quad-t1000=700,800,900
    \\quad-mid=400,500,600
    \\degen-cubic-250=100,200,300
    \\degen-cubic-500=100,200,300
    \\degen-cubic-750=100,200,300
    \\degen-quad-500=100,200,300
    \\math-isqrt=0 12 1000
    ++ "\n";

const codex_bitop_if_cond_stdout =
    \\count-ones 5: 2
    \\count-ones 255: 8
    \\count-nz 5: 2
    ++ "\n";

const codex_ble_att_encode_stdout =
    \\5
    ++ "\n";

const codex_bounded_sig_runtime_stdout =
    \\6
    \\9
    ++ "\n";

const codex_bs3_smoke_stdout =
    \\hello
    \\hi
    \\bye
    ++ "\n";

const codex_call_clobber_stdout =
    \\args 132
    \\eq False
    \\eqtrue True
    ++ "\n";

const codex_canopen_encode_stdout =
    \\4
    ++ "\n";

const codex_cap_manifest_derived_stdout =
    \\capability manifest derived from opening effects
    ++ "\n";

const codex_carddeck_shuffle_stdout =
    \\counts:        39 30 32 31 28 39 26 31
    \\min:           26
    \\max:           39
    \\every pos hit: True
    \\within 3x:     True
    \\alternations:  127
    \\not a stripe:  True
    ++ "\n";

const codex_chapter_pages_stdout =
    \\3
    ++ "\n";

const codex_circbuf_test_stdout =
    \\count=3 front=10 back=30
    \\overflow front=2 count=3
    \\after-pop=20 count=1
    \\list=1,2,3
    \\sum=600
    ++ "\n";

const codex_cite_override_quire_stdout =
    \\cite-shared 1 = 2
    ++ "\n";

const codex_cms_spread_stdout =
    \\keys:           40
    \\exact:          38
    \\worst estimate: 2
    \\cols used:      32 27 32 26
    \\mostly exact:   True
    \\rows spread:    True
    \\total:          40
    ++ "\n";

const codex_consistent_hash_balance_stdout =
    \\nodes=4
    \\entries=64
    \\per-node= 40 42 47 71
    \\min-share=40
    \\max-share=71
    \\every-node-used=yes
    ++ "\n";

const codex_convolution_identity_stdout =
    \\impulse-identity=100 200 300 400 500
    \\box3-on-constant=666 999 999 999 666
    \\lengths=5 5
    ++ "\n";

const codex_ctor_narrow_warn_stdout =
    \\42
    ++ "\n";

const codex_dnp3_encode_stdout =
    \\8
    ++ "\n";

const codex_effect_dotted_allow_stdout =
    \\result 42
    ++ "\n";

const codex_effect_positive_stdout =
    \\step one
    \\value 42
    \\shout 7
    ++ "\n";

const codex_effect_row_var_syntax_stdout =
    \\pure 42
    \\shout 21
    \\logged 42
    ++ "\n";

const codex_effect_widen_arg_stdout =
    \\widened
    ++ "\n";

const codex_effect_widen_scope_stdout =
    \\widened
    ++ "\n";

const codex_enip_encode_stdout =
    \\5
    ++ "\n";

const codex_eq_generic_fields_stdout =
    \\text-control     : yes
    \\concrete-control : yes
    \\one-param eq     : yes
    \\one-param ne     : no
    \\second param     : yes
    \\second param ne  : no
    ++ "\n";

const codex_eq_generic_recursive_stdout =
    \\text-control   : yes
    \\named-concrete : yes
    \\pair-generic   : yes
    \\box-text-eq    : yes
    \\box-text-ne    : no
    \\box-int-eq     : yes
    \\box-int-ne     : no
    \\box-nested     : yes
    \\box-depth-ne   : no
    ++ "\n";

const codex_eq_plain_sum_stdout =
    \\both eq : yes
    \\both ne : yes
    \\text eq : yes
    \\cross ne : yes
    \\sum field eq : yes
    \\sum field ne : yes
    ++ "\n";

const codex_eventbus_test_stdout =
    \\3/10 events
    \\boot-events=2
    \\last=[20] b: 2
    \\since-200=2
    \\overflow=3/3 events
    ++ "\n";

const codex_field_cache_text_lit_stdout =
    \\literal between two reads: 3
    \\empty literal between them: 3
    \\no literal to cross: 3
    ++ "\n";

const codex_fins_encode_stdout =
    \\4
    ++ "\n";

const codex_frameless_leaf_probe_stdout =
    \\add32=3671238039
    \\rotl32=3090952880
    \\gmul2=143
    \\block=2
    \\plusk=4294967302
    ++ "\n";

const codex_hart_encode_stdout =
    \\6
    ++ "\n";

const codex_ieee802154_encode_stdout =
    \\4
    ++ "\n";

const codex_if_in_arith_stdout =
    \\72
    \\68
    \\76
    ++ "\n";

const codex_inline_cost_based_stdout =
    \\inline-cost-based: 1122 3351 9 40
    ++ "\n";

const codex_inline_single_caller_stdout =
    \\wide 5
    \\arity4 10
    \\free 101
    \\shadowed 101
    ++ "\n";

const codex_int_literal_underscore_stdout =
    \\grouped: 1000000000000000000
    \\padded: 42
    ++ "\n";

const codex_iterate_test_stdout =
    \\5
    \\3
    \\2
    \\3
    \\3
    \\2
    ++ "\n";

const codex_iterate_zip_test_stdout =
    \\3
    \\11
    \\33
    \\40
    \\True
    \\False
    ++ "\n";

const codex_j1939_encode_stdout =
    \\5
    ++ "\n";

const codex_knx_encode_stdout =
    \\4
    ++ "\n";

const codex_leaf_let_if_stdout =
    \\nd 2 4 = 3
    \\nd 9 4 = 0
    \\nd 0 1 = 0
    ++ "\n";

const codex_leaf_mispredict_stdout =
    \\222
    \\-33
    ++ "\n";

const codex_let_else_scope_stdout =
    \\7018
    \\7098
    ++ "\n";

const codex_let_shadow_scope_stdout =
    \\9
    ++ "\n";

const codex_linear_branch_stdout =
    \\15 25 20 30 10 100
    ++ "\n";

const codex_linear_mint_container_stdout =
    \\1
    ++ "\n";

const codex_linear_poly_freeze_stdout =
    \\21 seven
    ++ "\n";

const codex_linear_smoke_stdout =
    \\42 21 56
    ++ "\n";

const codex_lir_binop_cross_stdout =
    \\diff: 5
    \\diff-neg: -5
    \\addup: 6
    \\chain-sub: 12
    \\scale: 21
    \\offset: 107
    \\poly: 30
    \\reuse: 18
    \\wide: 36
    \\wide-sub: 73
    \\via-call: 36
    ++ "\n";

const codex_lir_branch_cross_stdout =
    \\mn: 3
    \\mn-rev: 3
    \\mn-eq: 5
    \\mx: 9
    \\mx-eq: 5
    \\le-lt: 10
    \\le-eq: 10
    \\le-gt: 20
    \\ge-eq: 30
    \\ge-lt: 40
    \\ne-same: 60
    \\ne-diff: 50
    \\sgn-pos: 1
    \\sgn-zero: 0
    \\far-lo: 8
    \\far-hi: 7
    \\nest-hi: 2
    \\nest-mid: 1
    \\nest-lo: 0
    \\even: 1
    \\odd: 0
    \\even-neg: 1
    \\odd-neg: 0
    \\mod4: 1
    \\mod4-no: 0
    \\wide-t: 75
    \\wide-f: -4
    \\via-call: 13
    ++ "\n";

const codex_lir_call_cross_stdout =
    \\5
    \\-5
    \\-3
    \\3
    \\6
    \\10
    \\5
    \\13
    \\312
    \\231
    ++ "\n";

const codex_lir_check_stdout =
    \\7
    \\13
    \\16
    \\15
    \\1
    \\14
    \\2
    \\10
    \\200
    \\8
    \\5
    \\42
    \\0
    \\1
    \\0
    \\1
    \\0
    \\1
    \\1
    \\1
    \\0
    \\1
    \\0
    \\1
    \\0
    \\120
    \\240
    \\6
    \\6
    ++ "\n";

const codex_lir_frame_cross_stdout =
    \\regs-only: 6
    \\saved: -52
    \\saved-perm: 52
    \\spilled: 20
    \\spilled-perm: 28
    \\unused-first: 18
    \\swapped: -5
    \\via-call: -19
    ++ "\n";

const codex_lir_join_cross_stdout =
    \\3
    \\4
    \\11
    \\21
    \\60
    \\80
    \\11
    \\12
    \\13
    \\57
    \\58
    \\68
    ++ "\n";

const codex_lir_load_cross_stdout =
    \\75
    \\42
    \\0
    \\5
    \\6
    \\0
    \\7
    \\0
    \\10
    \\1
    \\607
    \\2
    \\7
    \\3
    \\41
    ++ "\n";

const codex_lir_nullary_cross_stdout =
    \\ident: 7
    \\konst: 42
    \\neg-konst: -7
    \\big-konst: 123456789
    \\pick2: 9
    \\pick-mid: 2
    \\pick-last: 3
    \\deep: 8
    \\via-call: 15
    ++ "\n";

const codex_lir_selector_smoke_stdout =
    \\7
    \\6
    \\7
    \\7
    \\-7
    \\8
    \\0
    \\120
    \\240
    \\6
    \\6
    ++ "\n";

const codex_lir_test_cross_stdout =
    \\1
    \\0
    \\1
    \\0
    \\1
    \\0
    \\100
    \\200
    \\1
    \\0
    \\1
    \\0
    \\1
    \\0
    \\1
    ++ "\n";

const codex_list_pattern_stdout =
    \\sum=15
    \\count=3
    \\head=42
    \\headE=0
    \\second=6
    \\secondE=0
    \\sumE=0
    ++ "\n";

const codex_list_tail_empty_stdout =
    \\empty-len 0
    \\three-len 2
    \\three-first 2
    \\three-last 3
    \\one-len 0
    ++ "\n";

const codex_literal_subpattern_stdout =
    \\int-0 10
    \\int-1 11
    \\int-7 17
    \\int-n 19
    \\txt-sin 20
    \\txt-cos 21
    \\txt-oth 29
    \\flag-t 30
    \\flag-f 31
    \\pair-0 40
    \\pair-hit 41
    \\pair-oth 42
    \\bare-0 50
    \\bare-1 51
    \\bare-n 59
    \\bare-sin 60
    \\bare-cos 61
    \\bare-oth 69
    \\done
    ++ "\n";

const codex_match_arms_per_line_stdout =
    \\one-line: onetwothreeother
    \\many-1: one
    \\many-2: two
    \\many-3: three
    \\many-4: four
    \\many-5: five
    \\many-6: six
    \\many-9: other
    ++ "\n";

const codex_mbus_encode_stdout =
    \\4
    ++ "\n";

const codex_melsec_encode_stdout =
    \\4
    ++ "\n";

const codex_mix_bits_stdout =
    \\ones/256:        131
    \\balanced:        True
    \\alternations:    130
    \\not a stripe:    True
    \\control alt:     255
    \\control striped: True
    \\range2 ones/256: 121
    \\range2 spread:   True
    ++ "\n";

const codex_mod_bound_return_stdout =
    \\34
    \\34
    \\4
    ++ "\n";

const codex_modprobe_stdout =
    \\pp 7,3 div=2 mod=1
    \\np -7,3 div=-2 mod=2
    \\pn 7,-3 div=-2 mod=1
    \\nn -7,-3 div=2 mod=2
    \\pp2 8,4 div=2 mod=0
    \\np2 -8,4 div=-2 mod=0
    \\np3 -1,8 div=0 mod=7
    \\pn3 1,-8 div=0 mod=1
    ++ "\n";

const codex_mut_borrow_transitive_stdout =
    \\24
    ++ "\n";

const codex_neg_int_parse_stdout =
    \\-5
    ++ "\n";

const codex_negation_abutment_stdout =
    \\arg-lit: -1
    \\arg-only: -5
    \\arg-var: -2
    \\three-args: 83
    \\sub: 5
    \\left-abut: 3
    \\hyphen-digit: 7
    \\paren: -1
    \\arrow: 8
    ++ "\n";

const codex_particle_spread_stdout =
    \\emitted=200
    \\modal-dy-share-sp64=1
    \\modal-dy-share-sp100=2
    \\sample-dy=8 22 -40
    \\independent=yes
    ++ "\n";

const codex_path_real_stdout =
    \\/src/main.codex
    \\main.codex
    \\main
    \\codex
    ++ "\n";

const codex_prose_consistency_stdout =
    \\Alice:100
    \\Bob:250
    \\size=16
    \\status=active
    \\total=350
    ++ "\n";

const codex_prose_smoke_stdout =
    \\answer: 42
    \\ok:42
    \\err:not found
    \\fields-12
    \\Hello, World!
    ++ "\n";

const codex_punctual_iot_stdout =
    \\threat-2500: 3
    \\threat-400: 0
    \\threat-3800: 4
    \\temp-2500: 91
    \\temp-400: 14
    \\temp-3800: 139
    \\byte1: 15
    \\byte2: 34
    \\byte3: 83
    \\checksum: 132
    ++ "\n";

const codex_punctual_smoke_stdout =
    \\42
    \\42
    \\42
    \\42
    ++ "\n";

const codex_real_literal_boundary_stdout =
    \\whole-19-parses : 123456789012345680
    \\frac-19-parses  : 2
    ++ "\n";

const codex_reservoir_uniform_stdout =
    \\counts:      58 40 57 42 49 59 52 41 39 55 58 63 43 54 52 46 56 51 48 37
    \\expected ea: 50
    \\min:         37
    \\max:         63
    \\total:       1000
    \\all sampled: True
    \\within 2x:   True
    ++ "\n";

const codex_revised_narrow_stdout =
    \\literal: 42 lit
    \\revised: 7 rev
    \\mixed: 99 mixed
    ++ "\n";

const codex_roc_early_return_predicate_stdout =
    \\True
    ++ "\n";

const codex_roc_fold_count_stdout =
    \\4
    ++ "\n";

const codex_roc_fold_empty_stdout =
    \\42
    ++ "\n";

const codex_roc_fold_product_stdout =
    \\24
    ++ "\n";

const codex_roc_fold_sum_stdout =
    \\10
    ++ "\n";

const codex_roc_recursive_var_stdout =
    \\6
    ++ "\n";

const codex_rv_arg_order_stdout =
    \\lit-lit: 5
    \\call-lit: 5
    \\lit-call: -5
    \\bin-call: 3
    \\bin2-call: 13
    ++ "\n";

const codex_rv_big_literal_stdout =
    \\at-boundary want 9223372034707292159 got 9223372034707292159
    \\past-boundary want 9223372034707292160 got 9223372034707292160
    \\max want 9223372036854775807 got 9223372036854775807
    \\max-1 want 9223372036854775806 got 9223372036854775806
    \\min want -9223372036854775808 got -9223372036854775808
    \\allf want -1 got -1
    \\just-over-32 want 2147483648 got 2147483648
    \\top-of-32 want 2147483647 got 2147483647
    \\bottom-of-32 want -2147483648 got -2147483648
    \\under-32 want -2147483649 got -2147483649
    ++ "\n";

const codex_rv_frameless_imm_stdout =
    \\254
    \\65024
    \\65253
    \\42496
    \\399
    \\254
    \\1278
    \\241
    ++ "\n";

const codex_rv_frameless_temp_stdout =
    \\32
    \\6
    \\134
    \\42
    \\3599
    ++ "\n";

const codex_rv_param_bind_stdout =
    \\first: 1
    \\second: 2
    \\of3-first: 1
    \\of3-mid: 2
    \\of3-last: 3
    ++ "\n";

const codex_rv_param_order_stdout =
    \\bound: 3
    \\swap: 3
    ++ "\n";

const codex_s7comm_encode_stdout =
    \\8
    ++ "\n";

const codex_scope_console_stdout =
    \\console scope holds
    \\a bare Console grant still covers Console.Write
    ++ "\n";

const codex_scope_let_arm_global_stdout =
    \\arm-scoped: GLOBAL
    ++ "\n";

const codex_sensor_data_stdout =
    \\dev01/temperature=23.5@1000
    \\humidity
    \\42
    \\true
    \\ALERT
    \\ALERT
    ++ "\n";

const codex_simplify_check_stdout =
    \\5
    \\1
    \\-4
    \\7
    \\5
    \\42
    \\100
    \\9
    \\2
    \\10
    ++ "\n";

const codex_sixlowpan_encode_stdout =
    \\4
    ++ "\n";

const codex_sntp_encode_stdout =
    \\5
    ++ "\n";

const codex_string_escape_quote_stdout =
    \\she said "hi" loudly
    ++ "\n";

const codex_tco_bitop_loop_stdout =
    \\loop-both: 7
    \\loop-a0: 7
    \\loop-none: 255
    \\loop-shru: 0
    \\loop-shl: 256
    \\loop-xor: 255
    \\loop-or: 255
    \\loop-shr: 0
    \\loop-not: 255
    \\loop-mod: 456
    \\loop-sub: 247
    \\loop-and3: 255
    ++ "\n";

const codex_tco_direct_arg_reads_stdout =
    \\acc=101
    ++ "\n";

const codex_tco_framed_append_stdout =
    \\01 start
    \\02 append-text 4
    \\03 done
    ++ "\n";

const codex_tco_nested_if_stdout =
    \\arm-then: 15
    \\after-arm: 17
    \\base: 999
    ++ "\n";

const codex_tco_shuffle_spill_stdout =
    \\turns=4
    ++ "\n";

const codex_text_eq_branches_stdout =
    \\eq-int same    1
    \\eq-int differ  0
    \\ne-int same    0
    \\ne-int differ  1
    \\eq-txt same    equal
    \\eq-txt differ  differs
    \\eq-bool same   yes
    \\eq-bool differ no
    \\control int    10
    ++ "\n";

const codex_text_fold_indexed_stdout =
    \\3
    \\01234
    \\3
    \\4
    ++ "\n";

const codex_tuple_syntax_stdout =
    \\30
    \\20 10
    \\1
    \\12
    \\300
    ++ "\n";

const codex_tvar_in_declared_type_stdout =
    \\73
    ++ "\n";

const codex_ui_sound_test_stdout =
    \\click square 800hz 50ms vol=500
    \\beep sine 440hz 200ms vol=700
    \\triangle
    \\empty=true count=2 notempty=false
    \\drained=true
    \\count=2
    \\peek=warning
    \\q-count=2 done=false
    ++ "\n";

const codex_wavelet_sort_aliasing_stdout =
    \\1
    \\2
    \\3
    \\4
    \\5
    \\done
    ++ "\n";

const codex_when_arm_nontail_stdout =
    \\map-sum: 30
    \\filter-sum: 6
    \\tail-loop: 115
    ++ "\n";

const codex_when_arm_tail_call_stdout =
    \\01 start
    \\02 if-tail 10
    \\03 when-nontail 10
    \\04 when-tail 10
    \\05 when-bare 10
    \\06 done
    ++ "\n";

const codex_when_bool_cross_stdout =
    \\spin2: 150
    \\spin3: 150
    \\cross: 115
    \\frm: 150
    ++ "\n";

const codex_when_bool_pattern_stdout =
    \\bare-true: 1
    \\bare-false: 1
    \\computed: 1
    \\both-arms-named: 9
    \\if-control: 1
    \\int-control: 1
    \\char-control: 1
    ++ "\n";

const codex_when_generic_field_stdout =
    \\b1-hit
    \\i1-hit
    \\b2-miss
    \\i2-miss
    ++ "\n";

const codex_zigbee_encode_stdout =
    \\4
    ++ "\n";

    .{ .id = 0, .suite = .codex, .name = "codex: act-let-scope", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_act_let_scope.roc", .stdout_exact = codex_act_let_scope_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: amp-after-call", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_amp_after_call.roc", .stdout_exact = codex_amp_after_call_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: arith-operand-order", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_arith_operand_order.roc", .stdout_exact = codex_arith_operand_order_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: arithmetic", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_arithmetic.roc", .stdout_exact = codex_arithmetic_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: arm64-boot-test", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_arm64_boot_test.roc", .stdout_exact = codex_arm64_boot_test_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: bezier-identity", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_bezier_identity.roc", .stdout_exact = codex_bezier_identity_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: bitop-if-cond", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_bitop_if_cond.roc", .stdout_exact = codex_bitop_if_cond_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: ble-att-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_ble_att_encode.roc", .stdout_exact = codex_ble_att_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: bounded-sig-runtime", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_bounded_sig_runtime.roc", .stdout_exact = codex_bounded_sig_runtime_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: bs3-smoke", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_bs3_smoke.roc", .stdout_exact = codex_bs3_smoke_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: call-clobber", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_call_clobber.roc", .stdout_exact = codex_call_clobber_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: canopen-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_canopen_encode.roc", .stdout_exact = codex_canopen_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: cap-manifest-derived", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_cap_manifest_derived.roc", .stdout_exact = codex_cap_manifest_derived_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: carddeck-shuffle", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_carddeck_shuffle.roc", .stdout_exact = codex_carddeck_shuffle_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: chapter-pages", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_chapter_pages.roc", .stdout_exact = codex_chapter_pages_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: circbuf-test", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_circbuf_test.roc", .stdout_exact = codex_circbuf_test_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: cite-override-quire", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_cite_override_quire.roc", .stdout_exact = codex_cite_override_quire_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: cms-spread", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_cms_spread.roc", .stdout_exact = codex_cms_spread_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: consistent-hash-balance", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_consistent_hash_balance.roc", .stdout_exact = codex_consistent_hash_balance_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: convolution-identity", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_convolution_identity.roc", .stdout_exact = codex_convolution_identity_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: ctor-narrow-warn", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_ctor_narrow_warn.roc", .stdout_exact = codex_ctor_narrow_warn_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: dnp3-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_dnp3_encode.roc", .stdout_exact = codex_dnp3_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: effect-dotted-allow", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_effect_dotted_allow.roc", .stdout_exact = codex_effect_dotted_allow_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: effect-positive", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_effect_positive.roc", .stdout_exact = codex_effect_positive_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: effect-row-var-syntax", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_effect_row_var_syntax.roc", .stdout_exact = codex_effect_row_var_syntax_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: effect-widen-arg", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_effect_widen_arg.roc", .stdout_exact = codex_effect_widen_arg_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: effect-widen-scope", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_effect_widen_scope.roc", .stdout_exact = codex_effect_widen_scope_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: enip-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_enip_encode.roc", .stdout_exact = codex_enip_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: eq-generic-fields", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_eq_generic_fields.roc", .stdout_exact = codex_eq_generic_fields_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: eq-generic-recursive", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_eq_generic_recursive.roc", .stdout_exact = codex_eq_generic_recursive_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: eq-plain-sum", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_eq_plain_sum.roc", .stdout_exact = codex_eq_plain_sum_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: eventbus-test", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_eventbus_test.roc", .stdout_exact = codex_eventbus_test_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: field-cache-text-lit", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_field_cache_text_lit.roc", .stdout_exact = codex_field_cache_text_lit_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: fins-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_fins_encode.roc", .stdout_exact = codex_fins_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: frameless-leaf-probe", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_frameless_leaf_probe.roc", .stdout_exact = codex_frameless_leaf_probe_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: hart-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_hart_encode.roc", .stdout_exact = codex_hart_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: ieee802154-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_ieee802154_encode.roc", .stdout_exact = codex_ieee802154_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: if-in-arith", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_if_in_arith.roc", .stdout_exact = codex_if_in_arith_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: inline-cost-based", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_inline_cost_based.roc", .stdout_exact = codex_inline_cost_based_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: inline-single-caller", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_inline_single_caller.roc", .stdout_exact = codex_inline_single_caller_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: int-literal-underscore", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_int_literal_underscore.roc", .stdout_exact = codex_int_literal_underscore_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: iterate-test", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_iterate_test.roc", .stdout_exact = codex_iterate_test_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: iterate-zip-test", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_iterate_zip_test.roc", .stdout_exact = codex_iterate_zip_test_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: j1939-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_j1939_encode.roc", .stdout_exact = codex_j1939_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: knx-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_knx_encode.roc", .stdout_exact = codex_knx_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: leaf-let-if", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_leaf_let_if.roc", .stdout_exact = codex_leaf_let_if_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: leaf-mispredict", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_leaf_mispredict.roc", .stdout_exact = codex_leaf_mispredict_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: let-else-scope", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_let_else_scope.roc", .stdout_exact = codex_let_else_scope_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: let-shadow-scope", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_let_shadow_scope.roc", .stdout_exact = codex_let_shadow_scope_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: linear-branch", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_linear_branch.roc", .stdout_exact = codex_linear_branch_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: linear-mint-container", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_linear_mint_container.roc", .stdout_exact = codex_linear_mint_container_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: linear-poly-freeze", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_linear_poly_freeze.roc", .stdout_exact = codex_linear_poly_freeze_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: linear-smoke", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_linear_smoke.roc", .stdout_exact = codex_linear_smoke_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-binop-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_binop_cross.roc", .stdout_exact = codex_lir_binop_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-branch-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_branch_cross.roc", .stdout_exact = codex_lir_branch_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-call-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_call_cross.roc", .stdout_exact = codex_lir_call_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-check", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_check.roc", .stdout_exact = codex_lir_check_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-frame-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_frame_cross.roc", .stdout_exact = codex_lir_frame_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-join-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_join_cross.roc", .stdout_exact = codex_lir_join_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-load-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_load_cross.roc", .stdout_exact = codex_lir_load_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-nullary-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_nullary_cross.roc", .stdout_exact = codex_lir_nullary_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-selector-smoke", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_selector_smoke.roc", .stdout_exact = codex_lir_selector_smoke_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: lir-test-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_lir_test_cross.roc", .stdout_exact = codex_lir_test_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: list-pattern", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_list_pattern.roc", .stdout_exact = codex_list_pattern_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: list-tail-empty", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_list_tail_empty.roc", .stdout_exact = codex_list_tail_empty_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: literal-subpattern", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_literal_subpattern.roc", .stdout_exact = codex_literal_subpattern_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: match-arms-per-line", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_match_arms_per_line.roc", .stdout_exact = codex_match_arms_per_line_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: mbus-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_mbus_encode.roc", .stdout_exact = codex_mbus_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: melsec-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_melsec_encode.roc", .stdout_exact = codex_melsec_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: mix-bits", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_mix_bits.roc", .stdout_exact = codex_mix_bits_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: mod-bound-return", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_mod_bound_return.roc", .stdout_exact = codex_mod_bound_return_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: modprobe", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_modprobe.roc", .stdout_exact = codex_modprobe_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: mut-borrow-transitive", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_mut_borrow_transitive.roc", .stdout_exact = codex_mut_borrow_transitive_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: neg-int-parse", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_neg_int_parse.roc", .stdout_exact = codex_neg_int_parse_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: negation-abutment", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_negation_abutment.roc", .stdout_exact = codex_negation_abutment_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: particle-spread", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_particle_spread.roc", .stdout_exact = codex_particle_spread_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: path-real", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_path_real.roc", .stdout_exact = codex_path_real_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: prose-consistency", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_prose_consistency.roc", .stdout_exact = codex_prose_consistency_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: prose-smoke", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_prose_smoke.roc", .stdout_exact = codex_prose_smoke_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: punctual-iot", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_punctual_iot.roc", .stdout_exact = codex_punctual_iot_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: punctual-smoke", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_punctual_smoke.roc", .stdout_exact = codex_punctual_smoke_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: real-literal-boundary", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_real_literal_boundary.roc", .stdout_exact = codex_real_literal_boundary_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: reservoir-uniform", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_reservoir_uniform.roc", .stdout_exact = codex_reservoir_uniform_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: revised-narrow", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_revised_narrow.roc", .stdout_exact = codex_revised_narrow_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: roc-early-return-predicate", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_roc_early_return_predicate.roc", .stdout_exact = codex_roc_early_return_predicate_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: roc-fold-count", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_roc_fold_count.roc", .stdout_exact = codex_roc_fold_count_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: roc-fold-empty", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_roc_fold_empty.roc", .stdout_exact = codex_roc_fold_empty_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: roc-fold-product", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_roc_fold_product.roc", .stdout_exact = codex_roc_fold_product_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: roc-fold-sum", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_roc_fold_sum.roc", .stdout_exact = codex_roc_fold_sum_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: roc-recursive-var", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_roc_recursive_var.roc", .stdout_exact = codex_roc_recursive_var_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: rv-arg-order", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_rv_arg_order.roc", .stdout_exact = codex_rv_arg_order_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: rv-big-literal", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_rv_big_literal.roc", .stdout_exact = codex_rv_big_literal_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: rv-frameless-imm", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_rv_frameless_imm.roc", .stdout_exact = codex_rv_frameless_imm_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: rv-frameless-temp", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_rv_frameless_temp.roc", .stdout_exact = codex_rv_frameless_temp_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: rv-param-bind", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_rv_param_bind.roc", .stdout_exact = codex_rv_param_bind_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: rv-param-order", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_rv_param_order.roc", .stdout_exact = codex_rv_param_order_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: s7comm-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_s7comm_encode.roc", .stdout_exact = codex_s7comm_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: scope-console", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_scope_console.roc", .stdout_exact = codex_scope_console_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: scope-let-arm-global", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_scope_let_arm_global.roc", .stdout_exact = codex_scope_let_arm_global_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: sensor-data", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_sensor_data.roc", .stdout_exact = codex_sensor_data_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: simplify-check", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_simplify_check.roc", .stdout_exact = codex_simplify_check_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: sixlowpan-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_sixlowpan_encode.roc", .stdout_exact = codex_sixlowpan_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: sntp-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_sntp_encode.roc", .stdout_exact = codex_sntp_encode_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: string-escape-quote", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_string_escape_quote.roc", .stdout_exact = codex_string_escape_quote_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tco-bitop-loop", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tco_bitop_loop.roc", .stdout_exact = codex_tco_bitop_loop_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tco-direct-arg-reads", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tco_direct_arg_reads.roc", .stdout_exact = codex_tco_direct_arg_reads_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tco-framed-append", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tco_framed_append.roc", .stdout_exact = codex_tco_framed_append_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tco-nested-if", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tco_nested_if.roc", .stdout_exact = codex_tco_nested_if_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tco-shuffle-spill", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tco_shuffle_spill.roc", .stdout_exact = codex_tco_shuffle_spill_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: text-eq-branches", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_text_eq_branches.roc", .stdout_exact = codex_text_eq_branches_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: text-fold-indexed", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_text_fold_indexed.roc", .stdout_exact = codex_text_fold_indexed_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tuple-syntax", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tuple_syntax.roc", .stdout_exact = codex_tuple_syntax_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: tvar-in-declared-type", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_tvar_in_declared_type.roc", .stdout_exact = codex_tvar_in_declared_type_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: ui-sound-test", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_ui_sound_test.roc", .stdout_exact = codex_ui_sound_test_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: wavelet-sort-aliasing", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_wavelet_sort_aliasing.roc", .stdout_exact = codex_wavelet_sort_aliasing_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: when-arm-nontail", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_when_arm_nontail.roc", .stdout_exact = codex_when_arm_nontail_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: when-arm-tail-call", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_when_arm_tail_call.roc", .stdout_exact = codex_when_arm_tail_call_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: when-bool-cross", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_when_bool_cross.roc", .stdout_exact = codex_when_bool_cross_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: when-bool-pattern", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_when_bool_pattern.roc", .stdout_exact = codex_when_bool_pattern_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: when-generic-field", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_when_generic_field.roc", .stdout_exact = codex_when_generic_field_stdout } } },
    .{ .id = 0, .suite = .codex, .name = "codex: zigbee-encode", .backend = .interpreter, .body = .{ .command = .{ .args = &.{"--opt=interpreter"}, .roc_file = "test/codex/codex_zigbee_encode.roc", .stdout_exact = codex_zigbee_encode_stdout } } },
