## JsGlue -- generate JavaScript readers for a Roc platform's types.
##
## Roc ships ZigGlue, RustGlue and CGlue; there is no JavaScript one, so a page
## that wants a Roc value has to be told the layout by hand. That is what
## `arcade/web/shapewire.js` is: a decoder written twice, once as
## `ShapeWire.pack` in Roc and once as a reader in JavaScript, with nothing
## checking that the two agree. This generates the reader instead.
##
##   roc glue glue/JsGlue.roc <out-dir> <platform>/main.roc
##
## What it emits is a plain script (not a module) defining `RocGlue`, because
## the arcade's pages load scripts with `<script src>`, and:
##
##   - one reader per type the platform's provided functions mention, reading
##     a value out of a DataView over the wasm memory;
##   - the signature of every provided function, as a comment, so a host author
##     can see what it is binding.
##
## **WASM IS 32-BIT**, so every layout fact used here is the `*32` one. The
## compiler carries both widths; a 64-bit host would take the others.
app [make_glue] { pf: platform glue }

import pf.Types exposing [Types]
import pf.File exposing [File]
import pf.AbiLayout

make_glue : List(Types) -> Try(List(File), Str)
make_glue = |types_list|
	match List.first(types_list) {
		Err(_) => Err("JsGlue: the compiler passed no type table")
		Ok(types) => Ok([File.{ name: "roc_glue.js", content: render(types) }])
	}

render : Types -> Str
render = |types| {
	entries = types.provides_entries
	Str.concat(
		Str.concat(header(types), readers(types)),
		footer(entries, types),
	)
}

header : Types -> Str
header = |_types|
	Str.concat(
		"// Generated by glue/JsGlue.roc. Do not edit; regenerate.\n//\n// Readers for the Roc values this platform hands a page. Each takes a\n",
		"// DataView over the wasm memory and a byte offset, and answers a plain\n// JavaScript value. Layouts are the compiler's own, for a 32-bit pointer.\nconst RocGlue = (() => {\n\n",
	)

## One reader per type mentioned by a provided function, in id order, so a
## reader is defined before anything that calls it.
readers : Types -> Str
readers = |types| {
	n = List.len(types.types)
	var $out = ""
	var $i = 0
	while $i < n {
		$out = Str.concat($out, reader(types, $i))
		$i = $i + 1
	}
	$out
}

## A type is readable when every part of it is. A function is not a value in
## memory; a rigid type variable is whatever an app chose and the platform
## never says. An aggregate is readable only if its parts are.
readable : Types, U64, U64 -> Bool
readable = |types, id, depth|
	if depth > 8 {
		Bool.False
	} else {
		match at(types, id).repr {
			RocFunction(_) => Bool.False
			RocUnknown(_) => Bool.False
			RocStr => Bool.False
			RocTagUnion(_) => all_tags_readable(types, AbiLayout.tag_layouts(at(types, id).layout), depth)
			RocDec => Bool.False
			# A box of something unreadable is still a handle a page can hold.
			RocBox(_) => Bool.True
			RocList(elem) => readable(types, elem, depth + 1)
			RocRecord(_) => all_readable(types, AbiLayout.record_fields(at(types, id).layout), depth)
			_ => Bool.True
		}
	}

all_readable : Types, List(_), U64 -> Bool
all_readable = |types, fields, depth| {
	n = List.len(fields)
	var $ok = Bool.True
	var $i = 0
	while $i < n {
		field = List.get(fields, $i) ?? crash("glue: field out of range")
		$ok = if field.is_padding { $ok } else { $ok and readable(types, field.type_id, depth + 1) }
		$i = $i + 1
	}
	$ok
}

reader : Types, U64 -> Str
reader = |types, id| {
	info = at(types, id)
	name = reader_name(id)
	match if readable(types, id, 0) { body(types, id, info.repr) } else { Skipped } {
		Skipped => ""
		Reads(expr) => "  // ${shape(info.repr)}\n  const ${name} = (view, at) => ${expr};\n\n"
	}
}

## The expression that reads one value of this type at `at`.
body : Types, U64, _ -> [Reads(Str), Skipped]
body = |types, id, repr|
	match repr {
		RocBool => Reads("view.getUint8(at) !== 0")
		RocU8 => Reads("view.getUint8(at)")
		RocU16 => Reads("view.getUint16(at, true)")
		RocU32 => Reads("view.getUint32(at, true)")
		RocU64 => Reads("view.getBigUint64(at, true)")
		RocI8 => Reads("view.getInt8(at)")
		RocI16 => Reads("view.getInt16(at, true)")
		RocI32 => Reads("view.getInt32(at, true)")
		RocI64 => Reads("view.getBigInt64(at, true)")
		RocF32 => Reads("view.getFloat32(at, true)")
		RocF64 => Reads("view.getFloat64(at, true)")
		RocUnit => Reads("null")
		RocBox(inner) =>
			if readable(types, inner, 0) {
				Reads("${reader_name(inner)}(view, view.getUint32(at, true))")
			} else {
				# An opaque model: a page can hold the pointer and hand it back.
				Reads("view.getUint32(at, true)")
			}
		RocList(elem) => Reads(list_body(types, elem))
		RocRecord(record) => Reads(record_body(types, id, record))
		RocTagUnion(_) => Reads(tag_union_body(types, id))
		_ => Skipped
	}

## Every variant's payload has to be readable before the union is, so a
## generated reader never references one that was skipped.
all_tags_readable : Types, List(_), U64 -> Bool
all_tags_readable = |types, tags, depth| {
	n = List.len(tags)
	var $ok = Bool.True
	var $i = 0
	while $i < n {
		tag = List.get(tags, $i) ?? crash("glue: tag out of range")
		fine = if List.is_empty(tag.payload_fields) {
			all_payloads_readable(types, tag.payload, depth)
		} else {
			all_readable(types, tag.payload_fields, depth)
		}
		$ok = if fine { $ok } else { Bool.False }
		$i = $i + 1
	}
	$ok
}

all_payloads_readable : Types, List(U64), U64 -> Bool
all_payloads_readable = |types, payload, depth| {
	n = List.len(payload)
	var $ok = Bool.True
	var $i = 0
	while $i < n {
		id = List.get(payload, $i) ?? crash("glue: payload out of range")
		$ok = if readable(types, id, depth + 1) { $ok } else { Bool.False }
		$i = $i + 1
	}
	$ok
}

## **A TAG UNION IS A DISCRIMINANT AND A PAYLOAD AT ONE ADDRESS.** The compiler
## commits to where the discriminant sits, how wide it is, and where each
## variant's payload fields land. None of that is guessable from the source --
## the variants are not in source order, they are in the order the compiler
## chose, each with the number it was given.
##
## A variant with no payload reads as `{ tag }`; one whose payload the source
## never named reads as `{ tag, value }`, which is what `Blend(Mode)` wants;
## one with named fields reads as `{ tag, ...those }`.
tag_union_body : Types, U64 -> Str
tag_union_body = |types, id| {
	layout = at(types, id).layout
	tags = AbiLayout.tag_layouts(layout)
	read = discriminant_read(AbiLayout.discriminant_size(layout), AbiLayout.discriminant_offset(layout, Pointer32))
	n = List.len(tags)
	var $arms = ""
	var $i = 0
	while $i < n {
		tag = List.get(tags, $i) ?? crash("glue: tag out of range")
		$arms = Str.concat($arms, "      case ${U64.to_str(tag.discriminant)}: return ${tag_value(tag)};\n")
		$i = $i + 1
	}
	Str.concat(
		Str.concat("{\n    switch (${read}) {\n", $arms),
		"      default: throw new Error('roc_glue: no variant ' + ${read});\n    }\n  }",
	)
}

## The discriminant, at its own offset and its own width.
discriminant_read : U64, U64 -> Str
discriminant_read = |size, offset|
	if size == 1 {
		"view.getUint8(at + ${U64.to_str(offset)})"
	} else if size == 2 {
		"view.getUint16(at + ${U64.to_str(offset)}, true)"
	} else {
		"view.getUint32(at + ${U64.to_str(offset)}, true)"
	}

## **A SINGLE PAYLOAD IS A TYPE, NOT A FIELD LIST.** `payload_fields` is
## empty for a variant carrying one thing -- `Disc({...})` carries one record
## -- and `payload` names its type instead, sitting at offset 0. A variant
## carrying several has the field list. Reading only `payload_fields`, as the
## first attempt did, silently produced `{ tag: "Disc" }` for every variant:
## seven correct-looking readers, none of which read anything.
tag_value : _ -> Str
tag_value = |tag|
	if List.is_empty(tag.payload_fields) and List.len(tag.payload) == 1 {
		single = List.get(tag.payload, 0) ?? crash("glue: payload out of range")
		Str.concat(Str.concat("({ tag: \"", tag.name), "\", value: ${reader_name(single)}(view, at + 0) })")
	} else {
		named_value(tag)
	}

named_value : _ -> Str
named_value = |tag| {
	fields = tag.payload_fields
	n = List.len(fields)
	var $out = ""
	var $i = 0
	while $i < n {
		field = List.get(fields, $i) ?? crash("glue: payload field out of range")
		$out = if field.is_padding {
			$out
		} else {
			Str.concat($out, " ${payload_name(field.name)}: ${reader_name(field.type_id)}(view, at + ${U64.to_str(field.offset32)}),")
		}
		$i = $i + 1
	}
	if Str.is_empty($out) {
		Str.concat(Str.concat("({ tag: \"", tag.name), "\" })")
	} else {
		Str.concat(Str.concat(Str.concat("({ tag: \"", tag.name), "\","), Str.concat($out, " })"))
	}
}

## A payload the source never named arrives as index "0"; `value` reads better.
payload_name : Str -> Str
payload_name = |name| if name == "0" { "value" } else { name }

## A list is a pointer, a length and a capacity; the elements sit end to end,
## each as wide as the compiler says that element is.
list_body : Types, U64 -> Str
list_body = |types, elem| {
	stride = at(types, elem).layout.size32
	Str.concat(
		"{\n    const start = view.getUint32(at, true);\n    const length = view.getUint32(at + 4, true);\n    const out = [];\n",
		"    for (let i = 0; i < length; i++) out.push(${reader_name(elem)}(view, start + i * ${U64.to_str(stride)}));\n    return out;\n  }",
	)
}

## A record is its fields, each at the offset the compiler committed to.
record_body : Types, U64, _ -> Str
record_body = |types, id, _record| {
	fields = AbiLayout.record_fields(at(types, id).layout)
	n = List.len(fields)
	var $out = "({"
	var $i = 0
	while $i < n {
		field = List.get(fields, $i) ?? crash("glue: field out of range")
		$out = if field.is_padding {
			$out
		} else {
			Str.concat($out, " ${field.name}: ${reader_name(field.type_id)}(view, at + ${U64.to_str(field.offset32)}),")
		}
		$i = $i + 1
	}
	Str.concat($out, " })")
}

footer : List(_), Types -> Str
footer = |entries, types| {
	n = List.len(entries)
	var $sigs = ""
	var $i = 0
	while $i < n {
		entry = List.get(entries, $i) ?? crash("glue: entry out of range")
		$sigs = Str.concat($sigs, "  //   ${entry.ffi_symbol} : ${shape(at(types, entry.type_id).repr)}\n")
		$i = $i + 1
	}
	sigs = $sigs
	Str.concat(
		Str.concat("  // What this platform provides:\n", sigs),
		"\n  return { ${exported(types)} };\n})();\n",
	)
}

## Every reader that got emitted, so a host can reach them by type id.
exported : Types -> Str
exported = |types| {
	n = List.len(types.types)
	var $out = ""
	var $i = 0
	while $i < n {
		$out = if readable(types, $i, 0) {
			if Str.is_empty($out) { reader_name($i) } else { Str.concat($out, ", ${reader_name($i)}") }
		} else {
			$out
		}
		$i = $i + 1
	}
	$out
}

## A one-line description of a type, for the comments.
shape : _ -> Str
shape = |repr|
	match repr {
		RocBool => "Bool"
		RocU8 => "U8"
		RocU16 => "U16"
		RocU32 => "U32"
		RocU64 => "U64"
		RocI8 => "I8"
		RocI16 => "I16"
		RocI32 => "I32"
		RocI64 => "I64"
		RocF32 => "F32"
		RocF64 => "F64"
		RocStr => "Str"
		RocDec => "Dec"
		RocUnit => "{}"
		RocBox(inner) => "Box(t${U64.to_str(inner)})"
		RocList(elem) => "List(t${U64.to_str(elem)})"
		RocRecord(_) => "a record"
		RocTagUnion(_) => "a tag union"
		RocFunction(f) => "${args_of(f.args)} -> t${U64.to_str(f.ret)}"
		RocUnknown(what) => "unknown (${what})"
		_ => "a vector"
	}

args_of : List(U64) -> Str
args_of = |args| {
	n = List.len(args)
	var $out = ""
	var $i = 0
	while $i < n {
		$out = Str.concat($out, "t${U64.to_str(List.get(args, $i) ?? 0)}")
		$out = if $i + 1 < n { Str.concat($out, ", ") } else { $out }
		$i = $i + 1
	}
	if n == 0 { "()" } else { $out }
}

reader_name : U64 -> Str
reader_name = |id| "read_t${U64.to_str(id)}"

at : Types, U64 -> _
at = |types, id| List.get(types.types, id) ?? crash("glue: type id out of range")
