#!/usr/bin/env python3
"""One BASIC program as its own Roc app.

    gen.py <suite> <name> <outdir>

Roc's default platform has no file or stdin effect, so the listing and the
keystrokes travel as string literals. The bound on the interpreter's fuel
is derived from the argument list so that the run happens in the compiled
backend rather than in the compile-time evaluator: this compiler evaluates
a call whose arguments are all known while it builds, and a BASIC game is
not a thing to ask it to do (roc-lang/roc#11334).
"""
import os, sys, pathlib

suite, name, outdir = sys.argv[1], sys.argv[2], pathlib.Path(sys.argv[3])
corpus = pathlib.Path(os.environ.get("BASIC_CORPUS", os.path.expanduser("~/build/basic-corpus"))) / suite
src = None
for ext in (".bas", ".BAS"):
    if (corpus / (name + ext)).exists():
        src = (corpus / (name + ext)).read_text(errors="replace")
        break
if src is None:
    sys.exit(f"no listing for {name}")
# The games carry their keystrokes in .input, the NBS programs in .in. A
# reply in basic/nbs-input, written from the listing's own prompts, replaces
# the corpus's -- which for some programs is a placeholder "0".
ours = pathlib.Path(__file__).resolve().parent / "nbs-input" / (name + ".in")
inp = ours.read_text() if suite == "nbs" and ours.exists() else ""
if not inp:
    for ext in (".input", ".in"):
        if (corpus / (name + ext)).exists():
            inp = (corpus / (name + ext)).read_text(errors="replace")
            break


def lit(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            continue
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 32 or ord(ch) > 126:
            out.append(" ")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


# The NBS suite grades ECMA-55; the games' captures are a microcomputer BASIC.
door = "run_ecma" if suite == "nbs" else "run"

lines = [l for l in inp.split("\n")]
if lines and lines[-1] == "":
    lines.pop()
(outdir / "Run.roc").write_text(
    f"""# {name} -- generated by basic/gen.py from the {suite} corpus. Do not edit.
import Basic

program : Str
program = {lit(src)}

keystrokes : List(Str)
keystrokes = [{", ".join(lit(l) for l in lines)}]

main! = |args| {{
\tseed = U64.plus_wrap(1, List.len(args))
\techo!(Basic.{door}(program, keystrokes, seed))
\tOk({{}})
}}
"""
)
