# Writes SquareValues.roc: every square's value to a piece of any color, from
# Steve's ranking to B1 (Rank.places) -- 100 points a place, the best square
# (B4) 6100, the worst (the pen) 0. Every color sees the same board from its
# own zone, so the table is red's.
#
#   cd fasttrack && roc gen_square_values.roc > SquareValues.roc
import Board
import Config
import Rank

colors : List(Str)
colors = ["red", "blue", "green", "purple"]

main! = |_args| {
	p = Rank.places(colors, "red", "B1")
	values = List.map(p.place, |place| if place == U64.highest { 0 } else { 100 * (U64.to_i64_wrap(p.worst) - U64.to_i64_wrap(place)) })
	zones = List.map_with_index(
		["own zone", "the next zone", "two zones on", "the zone before your own"],
		|title, z| {
			row = List.map_with_index(
				Config.config_locations,
				|l, s| "${l.id} ${I64.to_str(List.get(values, z * Board.per_zone + s) ?? 0)}",
			)
			"\t\t# ${title}: ${Str.join_with(row, ", ")}\n\t\t${Str.join_with(List.map(List.sublist(values, { start: z * Board.per_zone, len: Board.per_zone }), I64.to_str), ", ")},\n"
		},
	)
	bulls = List.get(values, 4 * Board.per_zone) ?? 0
	echo!(
		Str.join_with(
			[
				"# SquareValues -- GENERATED by gen_square_values.roc; do not edit.\n",
				"#\n",
				"# Every square's value to a piece, by Steve's ranking to B1 (Rank.places):\n",
				"# 100 points a place, the best square (B4) 6100, the worst (the pen) 0.\n",
				"# Laid out as Board.relative sees a square: the piece's own zone first, then the\n",
				"# zones after it, each in Config.config_locations order, then the\n",
				"# bullseye. Squares a piece never stands on (other colors' pens and\n",
				"# bases) are 0.\n",
				"import Board\n\n",
				"SquareValues :: [].{\n",
				"\tvalues : List(I64)\n",
				"\tvalues = [\n",
				Str.join_with(zones, ""),
				"\t\t# the bullseye\n\t\t${I64.to_str(bulls)},\n",
				"\t]\n\n",
				"\t## Square `s` to a piece of color `c` (its place in the color order).\n",
				"\tvalue : U64, U64 -> I64\n",
				"\tvalue = |c, s| List.get(values, Board.relative(c, s)) ?? 0\n",
				"}\n",
			],
			"",
		),
	)
	Ok({})
}
