# SquareValues -- GENERATED by gen_square_values.roc; do not edit.
#
# Every square's value to a piece, by Steve's ranking to B1 (Rank.places):
# 100 points a place, the best square (B4) 6100, the worst (the pen) 0.
# Laid out as Board.relative sees a square: the piece's own zone first, then the
# zones after it, each in Config.config_locations order, then the
# bullseye. Squares a piece never stands on (other colors' pens and
# bases) are 0.
import Board

SquareValues :: [].{
	values : List(I64)
	values = [
		# own zone: HP1 0, HP2 0, HP3 0, HP4 0, B1 5800, B2 5900, B3 6000, B4 6100, HH 1900, DS 5600, BR 5700, L0 2800, L1 2900, L2 2000, L3 2300, L4 3900, FT 4600, R0 5500, R1 4400, R2 4700, R3 4900, R4 4800
		0, 0, 0, 0, 5800, 5900, 6000, 6100, 1900, 5600, 5700, 2800, 2900, 2000, 2300, 3900, 4600, 5500, 4400, 4700, 4900, 4800,
		# the next zone: HP1 0, HP2 0, HP3 0, HP4 0, B1 0, B2 0, B3 0, B4 0, HH 1000, DS 1300, BR 1600, L0 600, L1 700, L2 2700, L3 3100, L4 4300, FT 5400, R0 1800, R1 2200, R2 1200, R3 300, R4 100
		0, 0, 0, 0, 0, 0, 0, 0, 1000, 1300, 1600, 600, 700, 2700, 3100, 4300, 5400, 1800, 2200, 1200, 300, 100,
		# two zones on: HP1 0, HP2 0, HP3 0, HP4 0, B1 0, B2 0, B3 0, B4 0, HH 1100, DS 1400, BR 1500, L0 500, L1 800, L2 2600, L3 3100, L4 4200, FT 5200, R0 1700, R1 2400, R2 2100, R3 400, R4 200
		0, 0, 0, 0, 0, 0, 0, 0, 1100, 1400, 1500, 500, 800, 2600, 3100, 4200, 5200, 1700, 2400, 2100, 400, 200,
		# the zone before your own: HP1 0, HP2 0, HP3 0, HP4 0, B1 0, B2 0, B3 0, B4 0, HH 3700, DS 3600, BR 3500, L0 3800, L1 4000, L2 4600, L3 5400, L4 5200, FT 5000, R0 3400, R1 3300, R2 3200, R3 2500, R4 900
		0, 0, 0, 0, 0, 0, 0, 0, 3700, 3600, 3500, 3800, 4000, 4600, 5400, 5200, 5000, 3400, 3300, 3200, 2500, 900,
		# the bullseye
		4100,
	]

	## Square `s` to a piece of color `c` (its place in the color order).
	value : U64, U64 -> I64
	value = |c, s| List.get(values, Board.relative(c, s)) ?? 0
}
